// -----------------------------------------------------------------------
// Copyright 2018 Autodesk, Inc. All rights reserved.
// 
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// -----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureCAMToNCSIMUL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureCAMToNCSIMUL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export data to NCSIMUL: there are errors in the document and nc code cannot be generated..
        /// </summary>
        internal static string msg_cannot_export_data {
            get {
                return ResourceManager.GetString("msg_cannot_export_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while exporting clamp to .stl file: .
        /// </summary>
        internal static string msg_clamp_export_exception {
            get {
                return ResourceManager.GetString("msg_clamp_export_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in FeatureCAM to NCSIMUL.
        /// </summary>
        internal static string msg_exception_title {
            get {
                return ResourceManager.GetString("msg_exception_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add toolbar button for FeatureCAM to NCSIMUL macro.
        /// </summary>
        internal static string msg_failed_to_add_toolbar_button {
            get {
                return ResourceManager.GetString("msg_failed_to_add_toolbar_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program failed to generate setup information..
        /// </summary>
        internal static string msg_failed_to_generate_setup_info {
            get {
                return ResourceManager.GetString("msg_failed_to_generate_setup_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove toolbar button for FeatureCAM to NCSIMUL macro.
        /// </summary>
        internal static string msg_failed_to_remove_toolbar_button {
            get {
                return ResourceManager.GetString("msg_failed_to_remove_toolbar_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save nc code.
        /// </summary>
        internal static string msg_failed_to_save_nc {
            get {
                return ResourceManager.GetString("msg_failed_to_save_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured: .
        /// </summary>
        internal static string msg_general_exception {
            get {
                return ResourceManager.GetString("msg_general_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If NCSIMUL machine file path is set, file must exist. File {0} doesn&apos;t exist. Please select existing file and try again..
        /// </summary>
        internal static string msg_machine_file_doesnot_exist {
            get {
                return ResourceManager.GetString("msg_machine_file_doesnot_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You either don&apos;t have a license for FeatureCAM to NCSIMUL module or it&apos;s not activated in the Evaluation Options dialog. Please check your Evaluation Options dialogs and contact your dealer for more information..
        /// </summary>
        internal static string msg_no_license {
            get {
                return ResourceManager.GetString("msg_no_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCSIMUL machine file has to be set.
        /// </summary>
        internal static string msg_no_machine_set {
            get {
                return ResourceManager.GetString("msg_no_machine_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find NCSIMUL on this computer. Cannot continue..
        /// </summary>
        internal static string msg_no_NCSIMUL {
            get {
                return ResourceManager.GetString("msg_no_NCSIMUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files are open.
        /// </summary>
        internal static string msg_no_open_files {
            get {
                return ResourceManager.GetString("msg_no_open_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select an item in the Order list.
        /// </summary>
        internal static string msg_no_Order_list_selection {
            get {
                return ResourceManager.GetString("msg_no_Order_list_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory path must be set. Please fix it and try again..
        /// </summary>
        internal static string msg_no_output_folder_set {
            get {
                return ResourceManager.GetString("msg_no_output_folder_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output written to: .
        /// </summary>
        internal static string msg_output_written_to {
            get {
                return ResourceManager.GetString("msg_output_written_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while exporting stock to .stl file: .
        /// </summary>
        internal static string msg_stock_export_exception {
            get {
                return ResourceManager.GetString("msg_stock_export_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Tools info was exported, but information for following tool(s) {0} was not exported completely, because the tool group(s) are unsupported by this addin..
        /// </summary>
        internal static string msg_unsupported_tools {
            get {
                return ResourceManager.GetString("msg_unsupported_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureCAM file name.
        /// </summary>
        internal static string str_file_name {
            get {
                return ResourceManager.GetString("str_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCSIMUL machine name.
        /// </summary>
        internal static string str_machine_name {
            get {
                return ResourceManager.GetString("str_machine_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureCAM postprocessor name.
        /// </summary>
        internal static string str_post_name {
            get {
                return ResourceManager.GetString("str_post_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureCAM to NCSIMUL.
        /// </summary>
        internal static string str_prog_name {
            get {
                return ResourceManager.GetString("str_prog_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup name (non-indexed parts).
        /// </summary>
        internal static string str_setup_name {
            get {
                return ResourceManager.GetString("str_setup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureCAM project title.
        /// </summary>
        internal static string str_title {
            get {
                return ResourceManager.GetString("str_title", resourceCulture);
            }
        }
    }
}
